import assert from 'node:assert/strict';
import {LiveScanSession} from '../src/utils/liveScanSession.js';
const corners={tl:{x:100,y:50},tr:{x:500,y:50},bl:{x:100,y:750},br:{x:500,y:750}};
const moved=Object.fromEntries(Object.entries(corners).map(([k,p])=>[k,{x:p.x+110,y:p.y}]));
const s=new LiveScanSession();
assert.equal(s.update('A,B',corners,1000,0),false);
assert.equal(s.update('A,B',corners,1000,200),true);
assert.equal(s.update('A,B',corners,1000,400),false,'Repeated a held sheet');
s.miss();assert.equal(s.update('A,B',corners,1000,600),false);
assert.equal(s.update('A,B',corners,1000,800),false,'One lost frame repeated the sheet');
s.miss();s.miss();
assert.equal(s.update('A,B',corners,1000,1000),false);
assert.equal(s.update('A,B',corners,1000,1200),true,'Identical answers after a gap did not re-arm');
assert.equal(s.update('B,C',corners,1000,1400),false);
assert.equal(s.update('B,C',corners,1000,1600),true,'A new answer pattern did not update');
assert.equal(s.update('B,C',moved,1000,1800),false,'Moving sheet scored before it settled');
assert.equal(s.update('B,C',moved,1000,2000),true,'Identical pattern in a new location did not re-arm');
assert.equal(s.update('C,D',moved,1000,2100),false);
assert.equal(s.update('C,D',moved,1000,2120),false,'Two near-simultaneous calls accepted a score');
assert.equal(s.update('C,D',moved,1000,2300),true);
console.log('Lightning stability, duplicate suppression, brief dropout, same-answer re-arm, movement and timing passed.');
