import {readFile,writeFile,unlink} from 'node:fs/promises';
import {resolve} from 'node:path';
const dir=resolve('dist');
let html=(await readFile(resolve(dir,'app-entry.html'),'utf8')).replace(/^[\t ]+$/gm,'');
const jsMatch=html.match(/<script\b[^>]*src="([^"]+)"[^>]*><\/script>/);
const cssMatch=html.match(/<link\b[^>]*href="([^"]+\.css)"[^>]*>/);
if(!jsMatch||!cssMatch)throw new Error('Expected one application bundle and stylesheet.');
const js=await readFile(resolve(dir,jsMatch[1].replace(/^\//,'')),'utf8');
const css=await readFile(resolve(dir,cssMatch[1].replace(/^\//,'')),'utf8');
html=html.replace(jsMatch[0],'').replace(cssMatch[0],()=>'<style>'+css.replace(/<\/style/gi,'<\\/style')+'</style>');
html=html.replace(/^[\t ]+$/gm,'');
html=html.replace('</body>',()=>'<script>'+js.replace(/<\/script/gi,'<\\/script')+'</script></body>');
html=html.replace('<div id="root"></div>','<noscript>QuickGrade needs JavaScript enabled to scan and grade bubble sheets.</noscript><div id="root"></div>');
if(/(?:src|href)="(?:\/assets|https?:)/.test(html))throw new Error('External asset reference remains.');
await writeFile('QuickGrade.html',html);
await writeFile('index.html',html);
await unlink(resolve(dir,'app-entry.html'));
await writeFile(resolve(dir,'index.html'),html);
console.log(`Packed standalone QuickGrade.html (${Math.round(Buffer.byteLength(html)/1024)} KB)`);
